SAVE_MODELS = True
SAVE_PLOTS = True
SAVE_VIDEOS = False

TRAINING_EPISODES = 5
WORKING_INTERVALS = 2
TEST_EPISODES = 1
MAX_STEPS = 100
MAX_DONE_COUNTER = 10
AGGREATION_TYPES = {1: "average", 2: "bad_worker", 3: "good_worker"}
AGGREATION_TYPE = AGGREATION_TYPES[2]
ROOMS_DIR = "9_9_4"
CUSTOM_PATH = f"{ROOMS_DIR}/tr{TRAINING_EPISODES}_x{WORKING_INTERVALS}_mSt{MAX_STEPS}_{AGGREATION_TYPE}"
PLOT_PATH = f"./plots/{CUSTOM_PATH}"
MOVIE_PATH = f"./movies/{CUSTOM_PATH}"
